fix: add skipLibCheck in `tsconfig.tns.json`
Currently when there is a web application and `ng add @nativescript/schematics` command is executed, the following error is thrown `ERROR in node_modules/@types/jasminewd2/index.d.ts(8,23): error TS2688: Cannot find type definition file for 'jasmine/v2'.`. Adding `skipLibCheck: true` will ensure that typescript will ignore `.d.ts` files from `node_modules`. As it requires too much efforts to add the option in `tsconfig.json`, we decided to add it inside `tsconfig.tns.json`.
As the option is added to `tsconfig.tns.json` file, there will be a difference compared to the behavior of `ng generate --collection=@nativescript/schematics [--shared]`:
* `ng generate --collection=@nativescript/schematics [--shared]` -> `skipLibCheck: true` is inside `tsconfig.json`
* `ng add @nativescript/schematics` -> `skipLibCheck: true` is inside `tsconfig.tns.json`

Rel to: https://github.com/NativeScript/nativescript-schematics/issues/249